# Nixpacks configuration for Coolify deployment

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "poppler_utils", "tesseract"]
aptPkgs = ["tesseract-ocr-ara"]

[start]
cmd = "python main.py prod --workers 4"
